import 'package:flutter/material.dart';

class AppColors {
  static ColorScheme lightScheme = ColorScheme.fromSwatch().copyWith(
    primary: const Color(0xFF00629E),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFCFE5FF),
    onPrimaryContainer: const Color(0xFF001D34),
    secondary: const Color(0xFF526070),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFD6E4F7),
    onSecondaryContainer: const Color(0xFF0F1D2A),
    tertiary: const Color(0xFF695779),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFF0DBFF),
    onTertiaryContainer: const Color(0xFF241532),
    error: const Color(0xFFBA1A1A),
    errorContainer: const Color(0xFFFFDAD6),
    onError: const Color(0xFFFFFFFF),
    onErrorContainer: const Color(0xFF410002),
    background: const Color(0xFFFCFCFF),
    onBackground: const Color(0xFF1A1C1E),
    surface: const Color(0xFFFCFCFF),
    onSurface: const Color(0xFF1A1C1E),
    surfaceVariant: const Color(0xFFDEE3EB),
    onSurfaceVariant: const Color(0xFF42474E),
    outline: const Color(0xFF73777F),
    onInverseSurface: const Color(0xFFF1F0F4),
    inverseSurface: const Color(0xFF2F3033),
    inversePrimary: const Color(0xFF9ACBFF),
    shadow: const Color(0xFF000000),
    surfaceTint: const Color(0xFF00629E),
    outlineVariant: const Color(0xFFC2C7CF),
    scrim: const Color(0xFF000000),
  );

  static ColorScheme darkScheme = ColorScheme.fromSwatch().copyWith(
      primary: const Color(0xFF9ACBFF),
      onPrimary: const Color(0xFF003355),
      primaryContainer: const Color(0xFF004A79),
      onPrimaryContainer: const Color(0xFFCFE5FF),
      secondary: const Color(0xFFBAC8DA),
      onSecondary: const Color(0xFF243240),
      secondaryContainer: const Color(0xFF3A4857),
      onSecondaryContainer: const Color(0xFFD6E4F7),
      tertiary: const Color(0xFFD4BEE5),
      onTertiary: const Color(0xFF392A49),
      tertiaryContainer: const Color(0xFF514060),
      onTertiaryContainer: const Color(0xFFF0DBFF),
      error: const Color(0xFFFFB4AB),
      errorContainer: const Color(0xFF93000A),
      onError: const Color(0xFF690005),
      onErrorContainer: const Color(0xFFFFDAD6),
      background: const Color(0xFF1A1C1E),
      onBackground: const Color(0xFFE2E2E5),
      surface: const Color(0xFF1A1C1E),
      onSurface: const Color(0xFFE2E2E5),
      surfaceVariant: const Color(0xFF42474E),
      onSurfaceVariant: const Color(0xFFC2C7CF),
      outline: const Color(0xFF8C9199),
      onInverseSurface: const Color(0xFF1A1C1E),
      inverseSurface: const Color(0xFFE2E2E5),
      inversePrimary: const Color(0xFF00629E),
      shadow: const Color(0xFF000000),
      surfaceTint: const Color(0xFF9ACBFF),
      outlineVariant: const Color(0xFF42474E),
      scrim: const Color(0xFF000000)
  );
}